Semana03/Semana03/Models/ErrorViewModel.cs
namespace Semana03.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Semana03/Semana03/Models/Estudiante.cs
namespace Semana03.Models
{
    public class Estudiante
    {
        public String Nombre { get; set; }
        public String Apellido { get; set; }
        public int Edad { get; set; }
        public String Carrera { get; set; }
    }
}

Semana03/Semana03/Controllers/EstudianteController.cs
using Microsoft.AspNetCore.Mvc;
using Semana03.Models;

namespace Semana03.Controllers
{
    public class EstudianteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CrearEstudiante(Estudiante estudiante) 
        {
            ViewBag.Titulo = "Información del Estudiante";

            return View("Detalle", estudiante);
        }
    }
}

Semana03/Semana03/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Semana03.Models;
using System.Diagnostics;

namespace Semana03.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Semana03/Semana03/Views/Estudiante/Detalle.cshtml
@model Estudiante
@{
    ViewData["Title"] = "Detalle";
}

<h1>Detalle del Estudiante</h1>
<!--Formas de Mostrar la fecha-->
@*h2>@DateTime.Now.ToShortDateString()</h2>*@
<h2>@DateTime.Now.ToString("dd/MM/yyyy")</h2>

<div class="container">
    <div class="card">
        <div class="card-title">@ViewBag.Titulo</div>
        <div class="card-body">XXX
            <div class="card-text">Nombre Completo: @Model.Nombre @Model.Apellido</div>
            <div class="card-text">Edad: @Model.Edad</div>
            <br />
            <br />
            <div class="footer">
                <span class="badge bg-info">@Model.Carrera</span>
            </div>
        </div>
    </div>
</div>

Semana03/Semana03/Views/Estudiante/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Crear un Estudiante</h1>
<br />
<br />
<!--Parametros: 1. Acción, 2. Controlador, 3 Metodo de Envio-->
@using (Html.BeginForm("CrearEstudiante", "Estudiante", FormMethod.Post))
{
        <div class="container">
            <div class="mb-3">
                <label for="nombre" class="col-form-label">Nombre:</label>
                <input type="text" name="nombre" class="form-control" placeholder="Digite el nombre del estudiante">
            </div>
            <div class="mb-3">
                <label for="apellido" class="col-form-label">Apellido:</label>
                <input type="text" name="apellido" class="form-control" placeholder="Digite el apellido del estudiante">
            </div>
            <div class="mb-3">
                <label for="edad" class="col-form-label">Edad:</label>
                <input type="number" name="edad" class="form-control" min="17">
            </div>
            <div class="mb-3">
                <label for="carrera" class="col-form-label">Carrera:</label>
                <select name="carrera" class="form-select" aria-label="Default select example">
                    <option selected value="Sistemas">Sistemas</option>
                    <option value="Medicina">Medicina</option>
                    <option value="Administración">Administración</option>
                </select>
            </div>

            <input type="submit" class="btn-primary" value="Crear">

        </div>
}

Semana03/Semana03/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <br />
    <br />
    <div class="container">
        <div class="row">
            <div class="col">Contenido 1</div>
            <div class="col">Contenido 2</div>
            <div class="col">Contenido 3</div>
            <div class="col">Contenido 4</div>
        </div>
    </div>
    <div class="row">
        <div class="col-6 bg-info">
            Hola
        </div>
        <div class="col-1 offset-2">
            <a class="btn" style="background-color:darkorchid">Cancelar</a>
        </div>
    </div>
</div>

Semana03/Semana03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Semana03</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Semana03.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Semana03</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiante" asp-action="Index">Estudiante</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Semana03 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>